"""One-off: regenerate tests/prompt_golden.json from the pre-refactor routes.py.

Pinned to the commit that still had the prompts inline. The original function
bodies are exec'd with stubbed collaborators and a fake client that records the
exact prompt string, so the golden file holds the real bytes rather than a
hand-retype (which is how "characters total." slipped in once already).

Not part of the test suite - run manually only if the prompts intentionally
change, then update the pinned commit below deliberately.
"""
import ast
import json
import pathlib
import subprocess
import sys
import types

PINNED = 'd7e1fce'          # commit where these prompts still lived in routes.py
OUT = pathlib.Path(__file__).parent / 'tests' / 'prompt_golden.json'

src = subprocess.run(['git', 'show', f'{PINNED}:studio/routes.py'],
                     capture_output=True, check=True).stdout.decode('utf-8')
lines = src.splitlines()
tree = ast.parse(src)

wanted = {}
for node in ast.walk(tree):
    if isinstance(node, ast.FunctionDef) and node.name in ('api_twitter_caption', 'api_outfit_scan'):
        start = min([node.lineno] + [d.lineno for d in node.decorator_list]) - 1
        wanted[node.name] = '\n'.join(lines[start:node.end_lineno])

if len(wanted) != 2:
    sys.exit(f'could not extract both functions from {PINNED} (got {sorted(wanted)})')


class Recorder:
    def __init__(self):
        self.prompts = []

    def generate(self, **kw):
        self.prompts.append(kw['prompt'])
        return {'response': 'a caption'}


rec = Recorder()
vibes = ['casual', 'simple', 'sexy', 'flirty', 'mysterious', 'funny', 'hype', 'professional']
lengths = ['short', 'medium', 'long']
ns = {
    'os': __import__('os'), 're': __import__('re'),
    'TWITTER_IMAGE_PATH': '__exists__', 'STUDIO': types.SimpleNamespace(selected_model='stub'),
    'resolve_model': lambda m: 'stub', 'client_for_model': lambda m: rec,
    'compress_image_b64': lambda *a, **k: 'b64', 'GPU_OPTIONS': {},
    'set_step': lambda *a: None, 'start_job': lambda name, work: work(),
    'HTTPException': type('HTTPException', (Exception,), {}),
    # swallow the @app.post(...) decorator so the function body can be exec'd
    'app': type('App', (), {m: (lambda self, *a, **k: (lambda f: f))
                             for m in ('get', 'post', 'put', 'delete')})(),
}

# TWITTER_IMAGE_PATH must pass os.path.exists
os_path_exists = ns['os'].path.exists
ns['os'] = types.SimpleNamespace(path=types.SimpleNamespace(exists=lambda p: True))

for name, code in wanted.items():
    exec(compile(code, f'{PINNED}:{name}', 'exec'), ns)

# caption: all 8 vibes x 3 lengths, plus fallback cases for unknown/empty input
caption = []
for v in vibes:
    for ln in lengths:
        rec.prompts.clear()
        ns['api_twitter_caption']({'vibe': v, 'length': ln})
        caption.append({'vibe': v, 'length': ln, 'prompt': rec.prompts[-1]})
for v, ln in (('nope', 'short'), ('casual', 'nope'), ('', ''), (None, None)):
    rec.prompts.clear()
    ns['api_twitter_caption']({'vibe': v, 'length': ln})
    caption.append({'vibe': v, 'length': ln, 'prompt': rec.prompts[-1],
                    'note': 'unknown input falls back to casual/medium'})

golden = {'caption': caption, 'vibe_prompts': {}, 'length_rules': {}}

# recover the lookup tables straight out of a rendered prompt
sample = caption[0]['prompt']
for entry in caption[:len(vibes) * len(lengths)]:
    tone = entry['prompt'].split('TONE: ')[1].split('\n')[0]
    if entry['length'] == 'medium':
        golden['vibe_prompts'][entry['vibe']] = tone
for ln in lengths:
    golden['length_rules'][ln] = next(
        e['prompt'].split('LENGTH: ')[1].split('\n')[0]
        for e in caption[:len(vibes) * len(lengths)] if e['vibe'] == 'casual' and e['length'] == ln)

# outfit: the scan runs synchronously through the start_job stub
ns['STUDIO'].outfit_image_path = '__exists__'
rec.prompts.clear()
ns['api_outfit_scan']()
golden['outfit'] = rec.prompts[-1]

golden['_note'] = (
    'Exact prompts as they existed before caption/outfit were extracted from '
    'studio/routes.py into shared modules. Generated by executing the original '
    'code, not by hand. tests/test_caption_prompts.py asserts the current '
    'implementation still produces these byte for byte.'
)

OUT.write_text(json.dumps(golden, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
print(f'wrote {OUT}  ({OUT.stat().st_size} bytes)')
print(f'  caption cases: {len(caption)}')
print(f'  outfit prompt: {len(golden["outfit"])} chars')
